const palette = {
  blue: '#074EE8',
  darkBlue: '#0D218B',
  lightBlue: '#DDE8FF',
  purple: '#6E40F0',
  lightPurple: ' #DFD5F9',
  offBlack: '#1D1D1D',
  offWhite: '#FFFBFE',
  grey: '#E7E7E7',
  darkGrey: '#777777',
  lightGrey: '#E7E7E7',
  green: '#0C7A2B',
  red: '#B3261E',
  beige: '#FFDABF',
  brown: '#B67458',
}

export const colors = {
  primary: palette.blue,
  primaryDark: palette.darkBlue,
  primaryLight: palette.lightBlue,
  secondary: palette.purple,
  secondaryLight: palette.lightPurple,
  text: palette.offBlack,
  textLight: palette.darkGrey,
  white: palette.offWhite,
  disabled: palette.grey,
  shadow: palette.lightGrey,
  success: palette.green,
  error: palette.red,
  transparent: 'rgba(255, 255, 255, 0)',
};
